### ISSUE TITLE
Ресайз картинок в markdown

### ISSUE THREAD

**Issue by zhovner** [Flipper-Zero/docs#22]
Ебучий markdown не поддерживает ресайз картинок. 
Хочу как здесь https://stackoverflow.com/questions/14675913/changing-image-size-in-markdown

```
![](./pic/pic1_50.png =100x20)
![](./pic/pic1s.png =250x)

```

**Comment by anna-oake** [comment]
`![](./pic/pic1s.png){width="250"}`
